using Aspire.Hosting.ApplicationModel;
using FeWoLearning.MicroServices.Exercises.Intermediate;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using static FeWoLearning.MicroServices.Exercises.Intermediate.Ex037_EfCoreAgainstPostgres;

namespace FeWoLearning.MicroServices.Tests.Intermediate;

public class Ex037_EfCoreAgainstPostgresTests
{
    [Fact]
    public void The_model_is_a_real_Postgres_database_child_and_not_a_lookalike_container()
    {
        var model = ModelHarness.Build(Configure);

        // Same rule as ex036, other flavour: AddContainer("pg", "postgres") plus
        // AddConnectionString renders a plausible string and is neither type.
        var server = Assert.IsType<PostgresServerResource>(model.Resource("pg"));
        var database = Assert.IsType<PostgresDatabaseResource>(model.Resource(DatabaseResourceName));
        Assert.Same(server, Assert.IsAssignableFrom<IResourceWithParent>(database).Parent);

        // Postgres writes two keyed clauses and fixes the login to "postgres"; SQL
        // Server joins host and port with a comma and fixes it to "sa". Asserting the
        // expression is what rejects a copy of ex036 with the names changed.
        Assert.Equal(
            "Host={pg.bindings.tcp.host};Port={pg.bindings.tcp.port};Username=postgres;"
            + "Password={pg-password.value}",
            ModelHarness.ConnectionString(server));
        Assert.Equal(
            $"{{pg.connectionString}};Database={DatabaseResourceName}",
            ModelHarness.ConnectionString(database));
    }

    [Fact]
    public void The_context_is_on_the_Npgsql_provider_and_carries_the_INJECTED_string()
    {
        // Invented microseconds ago, so a hardcoded "Host=localhost;Database=catalog"
        // has nothing to guess with.
        var sentinel = $"ex037-{Guid.NewGuid():N}";
        var injected = $"Host=nowhere;Port=5432;Database=catalog;Username=postgres;"
                       + $"Password=irrelevant;Application Name={sentinel}";

        var builder = Host.CreateApplicationBuilder();
        builder.Configuration[$"ConnectionStrings:{DatabaseResourceName}"] = injected;
        AddCatalogDbContext(builder);

        using var host = builder.Build();
        using var scope = host.Services.CreateScope();
        var context = scope.ServiceProvider.GetRequiredService<CatalogContext>();

        // Rejects a copy of ex036's UseSqlServer: both resolve a CatalogContext, and
        // only ProviderName says which provider was configured.
        Assert.Equal("Npgsql.EntityFrameworkCore.PostgreSQL", context.Database.ProviderName);
        Assert.Equal(injected, context.Database.GetConnectionString());
    }

    [Fact]
    public void The_two_providers_emit_DIFFERENT_SQL_for_the_SAME_model()
    {
        var sqlServer = CreateScript(CatalogProvider.SqlServer);
        var postgres = CreateScript(CatalogProvider.Postgres);

        // Same model on both sides: one table, three columns, one primary key. This is
        // what makes the row a COMPARISON rather than two unrelated scripts - and it
        // rejects the mutant that generates for a different entity per provider.
        Assert.Contains("CREATE TABLE [Products] (", sqlServer);
        Assert.Contains("CREATE TABLE \"Products\" (", postgres);
        foreach (var column in new[] { "Id", "Name", "CreatedAt" })
        {
            Assert.Contains($"[{column}]", sqlServer);
            Assert.Contains($"\"{column}\"", postgres);
        }

        // SQL Server's spellings, measured on EF Core 10.0.11.
        Assert.Contains("[Id] int NOT NULL IDENTITY", sqlServer);
        Assert.Contains("[Name] nvarchar(max) NOT NULL", sqlServer);
        Assert.Contains("[CreatedAt] datetime2 NOT NULL", sqlServer);
        Assert.Contains("CONSTRAINT [PK_Products] PRIMARY KEY ([Id])", sqlServer);
        // SQL Server batches with GO; Npgsql does not, and that is a real difference
        // between the two scripts rather than a formatting accident.
        Assert.Contains("GO", sqlServer);

        // Npgsql's, measured on Npgsql.EntityFrameworkCore.PostgreSQL 10.0.3. Note
        // "integer", not "int", and the standard identity clause rather than IDENTITY.
        Assert.Contains("\"Id\" integer GENERATED BY DEFAULT AS IDENTITY", postgres);
        Assert.Contains("\"Name\" text NOT NULL", postgres);
        Assert.Contains("\"CreatedAt\" timestamp with time zone NOT NULL", postgres);
        Assert.Contains("CONSTRAINT \"PK_Products\" PRIMARY KEY (\"Id\")", postgres);

        // ...and neither script may contain the other's. This half is what rejects the
        // laziest mutant of all - CreateScript ignoring its argument and configuring one
        // provider twice, which returns two byte-identical strings. Assert.NotEqual on
        // the two scripts would catch that one too, and nothing else; these do both.
        Assert.DoesNotContain("nvarchar", postgres);
        Assert.DoesNotContain("datetime2", postgres);
        Assert.DoesNotContain("GO", postgres);
        Assert.DoesNotContain("timestamp with time zone", sqlServer);
        Assert.DoesNotContain("GENERATED BY DEFAULT AS IDENTITY", sqlServer);
        Assert.DoesNotContain(" text NOT NULL", sqlServer);
    }

    [Fact]
    public void Each_provider_escapes_its_OWN_delimiter_in_a_schema_the_test_invented()
    {
        // One name, carrying both delimiters and a value that did not exist when the
        // exercise was written. Each provider must double ITS delimiter and leave the
        // other's alone - which is exactly what a hand-written script, or a
        // $"[{schema}]" template, gets wrong.
        var schema = $"ex037_{Guid.NewGuid():N}_a]b\"c";

        var sqlServer = CreateScript(CatalogProvider.SqlServer, schema);
        var postgres = CreateScript(CatalogProvider.Postgres, schema);

        // SQL Server: "]" doubles inside brackets, the double quote is left alone.
        var sqlServerDelimited = "[" + schema.Replace("]", "]]") + "]";
        Assert.Contains($"CREATE TABLE {sqlServerDelimited}.[Products] (", sqlServer);
        Assert.Contains($"IF SCHEMA_ID(N'{schema}') IS NULL", sqlServer);

        // Npgsql: the double quote doubles, "]" is left alone - and the schema is
        // created inside a DO $EF$ block, which SQL Server has no equivalent of.
        var postgresDelimited = "\"" + schema.Replace("\"", "\"\"") + "\"";
        Assert.Contains($"CREATE TABLE {postgresDelimited}.\"Products\" (", postgres);
        Assert.Contains("DO $EF$", postgres);

        // Belt and braces: the naive interpolation each provider must NOT have produced.
        Assert.DoesNotContain($"CREATE TABLE [{schema}]", sqlServer);
        Assert.DoesNotContain($"CREATE TABLE \"{schema}\"", postgres);

        // ...and the schema really is per-call rather than baked in once: the
        // unqualified script from the fact above must still be obtainable afterwards.
        Assert.Contains("CREATE TABLE [Products] (", CreateScript(CatalogProvider.SqlServer));
    }
}
