using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using Avalonia.Controls;
using Avalonia.Headless.XUnit;
using Avalonia.Threading;
using Avalonia.VisualTree;
using FeWoLearning.Avalonia.Exercises.Intermediate;
using FeWoLearning.Avalonia.Tests;

namespace FeWoLearning.Avalonia.Tests.Intermediate;

public class Ex056_DataGridColumnsTests
{
    private static (Ex056_DataGridColumns View, Ex056_DataGridColumnsViewModel Vm) Arrange()
    {
        var vm = new Ex056_DataGridColumnsViewModel();
        var view = ViewHarness.Show(new Ex056_DataGridColumns { DataContext = vm }, 400, 250);
        return (view, vm);
    }

    // Excludes the column-header row's own TextBlocks, so only the data cells
    // remain - the header row renders as TextBlocks too, and would otherwise
    // pollute every text-based assertion below.
    private static List<string?> DataCellTexts(DataGrid grid) =>
        grid.GetVisualDescendants()
            .OfType<TextBlock>()
            .Where(t => t.FindAncestorOfType<DataGridColumnHeader>() is null)
            .Select(t => t.Text)
            .ToList();

    // Mechanism check: AutoGenerateColumns="True" produces two columns with the
    // same headers without the learner declaring any - IsAutoGenerated is what
    // tells the two apart, and it is false only for explicitly declared columns.
    [AvaloniaFact]
    public void Grid_Has_Two_Explicitly_Declared_NonAutoGenerated_Columns()
    {
        var (view, vm) = Arrange();
        var grid = view.FindControl<DataGrid>("Grid");

        Assert.NotNull(grid);
        Assert.Same(vm.Rows, grid!.ItemsSource);
        Assert.Equal(2, grid.Columns.Count);
        Assert.All(grid.Columns, c => Assert.False(c.IsAutoGenerated));
        Assert.Equal(["Name", "Age"], grid.Columns.Select(c => c.Header).ToList());
        Assert.All(grid.Columns, c => Assert.IsType<DataGridTextColumn>(c));
    }

    [AvaloniaFact]
    public void Renders_Every_Row_Through_The_Declared_Columns()
    {
        var (view, _) = Arrange();
        var grid = view.FindControl<DataGrid>("Grid")!;

        Assert.Equal(
            ["Grace", "45", "Ada", "36", "Linus", "54"],
            DataCellTexts(grid));
    }

    // The real discriminator for "sorting": the row collection is deliberately
    // NOT pre-sorted either way (Grace, Ada, Linus), so any reordering after
    // driving Sort must be a genuine re-sort by Name, not a coincidence of the
    // source order. There is no real header click in a headless test, so the
    // column is driven directly - the SAME mechanism a real header click uses
    // internally. Whichever literal direction the package's Sort(direction)
    // measures out to (this package's own convention, not asserted here), the
    // row order must both change from the untouched arrange AND land in a
    // genuine alphabetical order by Name - a cheat that never re-sorts, or
    // that reorders by something other than Name, satisfies neither.
    [AvaloniaFact]
    public void Sorting_The_Name_Column_Reorders_Rows_Into_Alphabetical_Order()
    {
        var (view, _) = Arrange();
        var grid = view.FindControl<DataGrid>("Grid")!;
        Dispatcher.UIThread.RunJobs();

        var before = DataCellTexts(grid);

        grid.Columns[0].Sort(ListSortDirection.Ascending);
        Dispatcher.UIThread.RunJobs();

        var after = DataCellTexts(grid);
        Assert.NotEqual(before, after);

        var names = after.Where((_, i) => i % 2 == 0).Select(n => n!).ToList();
        var ascending = names.OrderBy(n => n, System.StringComparer.Ordinal).ToList();
        var descending = names.OrderByDescending(n => n, System.StringComparer.Ordinal).ToList();
        Assert.True(
            names.SequenceEqual(ascending) || names.SequenceEqual(descending),
            $"expected Name column sorted alphabetically either way, got [{string.Join(",", names)}]");
    }
}
