using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using Avalonia.Controls;
using Avalonia.Headless.XUnit;
using Avalonia.Threading;
using Avalonia.VisualTree;
using FeWoLearning.Avalonia.Exercises.Intermediate;
using FeWoLearning.Avalonia.Tests;

namespace FeWoLearning.Avalonia.Tests.Intermediate;

public class Ex056_DataGridColumnsTests
{
    private static (Ex056_DataGridColumns View, Ex056_DataGridColumnsViewModel Vm) Arrange()
    {
        var vm = new Ex056_DataGridColumnsViewModel();
        var view = ViewHarness.Show(new Ex056_DataGridColumns { DataContext = vm }, 400, 250);
        return (view, vm);
    }

    // Reads a cell's rendered text through the OWNING column rather than by
    // visual-tree position, so nothing here depends on which of the two
    // declared columns was written first - column order is not part of what
    // this exercise grades.
    private static string? CellText(DataGridColumn column, DataGridRow row) =>
        column.GetCellContent(row) switch
        {
            TextBlock tb => tb.Text,
            var content => content?.ToString(),
        };

    // Mechanism check: AutoGenerateColumns="True" produces two columns with the
    // same headers without the learner declaring any - IsAutoGenerated is what
    // tells the two apart, and it is false only for explicitly declared columns.
    // Headers are checked as a set: which column comes first is not graded.
    [AvaloniaFact]
    public void Grid_Has_Two_Explicitly_Declared_NonAutoGenerated_Columns()
    {
        var (view, vm) = Arrange();
        var grid = view.FindControl<DataGrid>("Grid");

        Assert.NotNull(grid);
        Assert.Same(vm.Rows, grid!.ItemsSource);
        Assert.Equal(2, grid.Columns.Count);
        Assert.All(grid.Columns, c => Assert.False(c.IsAutoGenerated));
        Assert.All(grid.Columns, c => Assert.IsType<DataGridTextColumn>(c));
        Assert.Equal(new HashSet<object?> { "Name", "Age" }, new HashSet<object?>(grid.Columns.Select(c => c.Header)));
    }

    [AvaloniaFact]
    public void Renders_Every_Row_Through_The_Declared_Columns()
    {
        var (view, vm) = Arrange();
        var grid = view.FindControl<DataGrid>("Grid")!;
        Dispatcher.UIThread.RunJobs();

        var nameColumn = grid.Columns.Single(c => Equals(c.Header, "Name"));
        var ageColumn = grid.Columns.Single(c => Equals(c.Header, "Age"));
        var rows = grid.GetVisualDescendants().OfType<DataGridRow>().ToList();

        Assert.Equal(vm.Rows.Count, rows.Count);
        for (var i = 0; i < vm.Rows.Count; i++)
        {
            Assert.Equal(vm.Rows[i].Name, CellText(nameColumn, rows[i]));
            Assert.Equal(vm.Rows[i].Age.ToString(), CellText(ageColumn, rows[i]));
        }
    }

    // The real discriminator for "sorting": the row collection is deliberately
    // NOT pre-sorted either way (Grace, Ada, Linus), so any reordering after
    // driving Sort must be a genuine re-sort by Name, not a coincidence of the
    // source order. There is no real header click in a headless test, so the
    // column is driven directly - the SAME mechanism a real header click uses
    // internally. The Name column is looked up by header, not by position, so
    // this does not assume which of the two declared columns comes first.
    // Whichever literal direction the package's Sort(direction) measures out to
    // (this package's own convention, not asserted here), the row order must
    // both change from the untouched arrange AND land in a genuine alphabetical
    // order by Name - a cheat that never re-sorts, or that reorders by
    // something other than Name, satisfies neither.
    [AvaloniaFact]
    public void Sorting_The_Name_Column_Reorders_Rows_Into_Alphabetical_Order()
    {
        var (view, vm) = Arrange();
        var grid = view.FindControl<DataGrid>("Grid")!;
        Dispatcher.UIThread.RunJobs();

        var nameColumn = grid.Columns.Single(c => Equals(c.Header, "Name"));
        var before = grid.GetVisualDescendants().OfType<DataGridRow>()
            .Select(r => CellText(nameColumn, r)).ToList();

        nameColumn.Sort(ListSortDirection.Ascending);
        Dispatcher.UIThread.RunJobs();

        var after = grid.GetVisualDescendants().OfType<DataGridRow>()
            .Select(r => CellText(nameColumn, r)).ToList();

        Assert.NotEqual(before, after);
        Assert.Equal(vm.Rows.Count, after.Count);

        var names = after.Select(n => n!).ToList();
        var ascending = names.OrderBy(n => n, System.StringComparer.Ordinal).ToList();
        var descending = names.OrderByDescending(n => n, System.StringComparer.Ordinal).ToList();
        Assert.True(
            names.SequenceEqual(ascending) || names.SequenceEqual(descending),
            $"expected Name column sorted alphabetically either way, got [{string.Join(",", names)}]");
    }
}
