using Aspire.Hosting;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

namespace FeWoLearning.MicroServices.Exercises.Intermediate;

/// <summary>
/// Goal:   Move ex036's DbContext - the same entity, the same mapping - onto Npgsql,
///         and then look at what the two providers actually emit. "EF Core is
///         database-agnostic" is true about your C#; it is not true about your schema.
/// Drills: `AddPostgres` + `AddDatabase` and `UseNpgsql` on the service side; then
///         `DatabaseFacade.GenerateCreateScript()` twice, once per provider, with no
///         database anywhere - the same operations `dotnet ef migrations script` would
///         emit, obtained in-process in milliseconds.
/// Passes: the Postgres half of the model is a PostgresServerResource plus a
///         PostgresDatabaseResource; the context resolves on
///         Npgsql.EntityFrameworkCore.PostgreSQL carrying the injected string; and the
///         two scripts describe the same table with different SQL - `nvarchar(max)` /
///         `datetime2` / `IDENTITY` against `text` / `timestamp with time zone` /
///         `GENERATED BY DEFAULT AS IDENTITY` - each carrying NONE of the other's
///         spellings.
/// Note:   Every fact here is offline. Nothing connects: GenerateCreateScript reads the
///         model and the provider's SQL generator, so a connection string that points
///         nowhere is fine and no container is needed. That is the point of the row -
///         the difference between two providers is knowable before anything runs.
///
///         The fourth fact is the one a hand-written pair of SQL strings cannot fake.
///         The test passes a schema name it invented, containing both a `]` and a `"`,
///         and requires each provider to escape its OWN delimiter and leave the other's
///         alone: SQL Server writes `[a]]b"c]`, Npgsql writes `"a]b""c"`. A template
///         like $"[{schema}]" produces `[a]b"c]` and fails; measured on EF Core 10.0.11
///         and Npgsql.EntityFrameworkCore.PostgreSQL 10.0.3.
///
///         `Schema` and the ModelCacheKeyFactory below are scaffolding, not the TODO.
///         EF caches the built model per (context type, provider), so two schemas would
///         otherwise share one cached model and the second call would silently return
///         the first one's script - measured, and it is why the naive version of this
///         row graded nothing.
/// </summary>
public static class Ex037_EfCoreAgainstPostgres
{
    /// <summary>The RESOURCE name, hence the configuration key <c>ConnectionStrings:catalog</c>.</summary>
    public const string DatabaseResourceName = "catalog";

    /// <summary>Which provider <see cref="CreateScript"/> should generate for.</summary>
    public enum CatalogProvider
    {
        SqlServer,
        Postgres
    }

    public sealed class Product
    {
        public int Id { get; set; }
        public string Name { get; set; } = "";
        public DateTime CreatedAt { get; set; }
    }

    public sealed class CatalogContext(DbContextOptions<CatalogContext> options) : DbContext(options)
    {
        /// <summary>
        /// Scaffolding. Set only by <see cref="CreateScript"/>; DI leaves it null, so a
        /// context resolved from the container is mapped exactly like ex036's.
        /// </summary>
        public string? Schema { get; init; }

        public DbSet<Product> Products => Set<Product>();

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            if (Schema is not null)
            {
                modelBuilder.HasDefaultSchema(Schema);
            }
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            => optionsBuilder.ReplaceService<IModelCacheKeyFactory, SchemaAwareModelCacheKeyFactory>();
    }

    /// <summary>
    /// Scaffolding: puts <see cref="CatalogContext.Schema"/> into EF's model cache key,
    /// so that generating for two schemas does not hand back one cached model twice.
    /// </summary>
    public sealed class SchemaAwareModelCacheKeyFactory : IModelCacheKeyFactory
    {
        public object Create(DbContext context, bool designTime)
            => (context.GetType(), (context as CatalogContext)?.Schema, designTime);
    }

    public static void Configure(IDistributedApplicationBuilder builder)
        => throw new NotImplementedException(
            "TODO: ex037 - add a PostgreSQL server \"pg\" carrying a database whose resource "
            + "name is DatabaseResourceName.");

    /// <summary>
    /// Registers <see cref="CatalogContext"/> on Npgsql, reading the connection string
    /// the AppHost injected as <c>ConnectionStrings:catalog</c>.
    /// </summary>
    public static void AddCatalogDbContext(IHostApplicationBuilder builder)
        => throw new NotImplementedException(
            "TODO: ex037 - register CatalogContext with UseNpgsql over the injected "
            + "ConnectionStrings:catalog.");

    /// <summary>
    /// The CREATE script <paramref name="provider"/> would run to build this model, with
    /// an optional default <paramref name="schema"/>. Generated offline - nothing
    /// connects, so the connection string you configure the provider with is irrelevant
    /// and must never be opened.
    /// </summary>
    public static string CreateScript(CatalogProvider provider, string? schema = null)
        => throw new NotImplementedException(
            "TODO: ex037 - build a CatalogContext on the requested provider (pass any "
            + "connection string; it is never opened) and return "
            + "context.Database.GenerateCreateScript().");
}
