using Aspire.Hosting;
using Microsoft.EntityFrameworkCore;

namespace FeWoLearning.MicroServices.Exercises.Intermediate;

/// <summary>
/// Goal:   Write the two pieces of EF Core that only ever bite in production: a
///         multi-statement transaction that is safe to RETRY, and optimistic
///         concurrency that actually detects a lost update.
/// Drills: `EnableRetryOnFailure` and `Database.CreateExecutionStrategy()`;
///         `strategy.ExecuteAsync(...)` wrapped around
///         `BeginTransactionAsync` / two `SaveChangesAsync` / `CommitAsync`; and
///         `IsRowVersion()`, SQL Server's `rowversion` column, whose value the server
///         changes on every UPDATE.
/// Passes: offline - the model carries a rowversion concurrency token generated
///         OnAddOrUpdate, and the context's execution strategy retries on failure. At
///         L3 - a transfer moves money; a failure injected BETWEEN the two saves leaves
///         both balances exactly as they were, while a dirty read taken at that moment
///         proves the debit had really been written; and two interleaved updates make
///         the second saver throw DbUpdateConcurrencyException with no lost update.
/// Note:   Three traps, all measured.
///
///         (1) Once retries are enabled, `BeginTransactionAsync` on its own THROWS -
///         "the configured execution strategy 'SqlServerRetryingExecutionStrategy' does
///         not support user-initiated transactions". That is EF telling you a retry
///         would replay half a transaction. So "did the learner use the strategy" needs
///         no clever assertion: without it, the transfer cannot even start.
///
///         (2) `betweenSaves` and `afterLoad` are seams, and they exist because
///         concurrency tests that rely on wall-clock timing are flaky by construction.
///         There is no sleep and no second thread anywhere in this row: the test
///         supplies a callback, and the interleaving is therefore exactly as ordered as
///         a single-threaded program. Production callers pass null.
///
///         (3) A rowversion is generated by the SERVER, not by you - never assign it.
///         `[ConcurrencyCheck]` on Balance would also make two conflicting balance
///         updates collide, which is why the offline fact reads the column type rather
///         than merely asserting that something is a concurrency token.
/// </summary>
public static class Ex040_TransactionsAndConcurrency
{
    /// <summary>The RESOURCE name, hence the configuration key <c>ConnectionStrings:catalog</c>.</summary>
    public const string DatabaseResourceName = "catalog";

    public sealed class Account
    {
        public int Id { get; set; }
        public string Name { get; set; } = "";
        public decimal Balance { get; set; }

        /// <summary>
        /// The concurrency token. SQL Server assigns it on INSERT and reassigns it on
        /// every UPDATE; your code never writes it.
        /// </summary>
        public byte[] RowVersion { get; set; } = [];
    }

    public sealed class CatalogContext(DbContextOptions<CatalogContext> options) : DbContext(options)
    {
        public DbSet<Account> Accounts => Set<Account>();

        protected override void OnModelCreating(ModelBuilder modelBuilder)
            => ConfigureConcurrencyToken(modelBuilder);
    }

    /// <summary>
    /// Makes <see cref="Account.RowVersion"/> the entity's concurrency token, backed by
    /// SQL Server's <c>rowversion</c> type.
    /// </summary>
    private static void ConfigureConcurrencyToken(ModelBuilder modelBuilder)
        => throw new NotImplementedException(
            "TODO: ex040 - make Account.RowVersion a rowversion concurrency token.");

    /// <summary>
    /// The options every operation in this row uses: SQL Server over
    /// <paramref name="connectionString"/>, with the retrying execution strategy on.
    /// </summary>
    public static DbContextOptions<CatalogContext> CreateOptions(string connectionString)
        => throw new NotImplementedException(
            "TODO: ex040 - UseSqlServer with EnableRetryOnFailure.");

    /// <summary>
    /// Moves <paramref name="amount"/> from one account to another as ONE unit: debit
    /// and credit are saved separately, inside a single explicit transaction, and the
    /// whole thing runs through the context's execution strategy so a transient failure
    /// replays all of it rather than half of it.
    /// </summary>
    /// <param name="betweenSaves">
    /// Test seam. Invoked after the debit has been saved and before the credit is - so
    /// throwing from it must leave the database exactly as it was found. Pass null in
    /// production code.
    /// </param>
    public static Task TransferAsync(
        string connectionString,
        int fromAccountId,
        int toAccountId,
        decimal amount,
        Func<Task>? betweenSaves,
        CancellationToken cancellationToken)
        => throw new NotImplementedException(
            "TODO: ex040 - run an explicit transaction through "
            + "Database.CreateExecutionStrategy().ExecuteAsync, saving the debit and the "
            + "credit separately and invoking betweenSaves in between.");

    /// <summary>
    /// Loads one account, adds <paramref name="delta"/> to its balance and saves.
    /// </summary>
    /// <param name="afterLoad">
    /// Test seam. Invoked while this context is holding a copy of the row and before it
    /// saves, so that another writer can get in first. Pass null in production code.
    /// </param>
    /// <returns>The row's new balance.</returns>
    /// <exception cref="DbUpdateConcurrencyException">
    /// Thrown when the row changed between the load and the save.
    /// </exception>
    public static Task<decimal> AddToBalanceAsync(
        string connectionString,
        int accountId,
        decimal delta,
        Func<Task>? afterLoad,
        CancellationToken cancellationToken)
        => throw new NotImplementedException(
            "TODO: ex040 - load, invoke afterLoad, then save. Do NOT catch the "
            + "concurrency exception; the caller is what decides how to resolve it.");

    public static void Configure(IDistributedApplicationBuilder builder)
        => throw new NotImplementedException(
            "TODO: ex040 - add a SQL Server \"sqldata\" carrying a database whose resource "
            + "name is DatabaseResourceName.");
}
