using Aspire.Hosting;
using Microsoft.EntityFrameworkCore;

namespace FeWoLearning.MicroServices.Exercises.Intermediate;

/// <summary>
/// Goal:   Write the two pieces of EF Core that only ever bite in production: a
///         multi-statement transaction that is safe to RETRY, and optimistic
///         concurrency that actually detects a lost update.
/// Drills: `EnableRetryOnFailure` and `Database.CreateExecutionStrategy()`;
///         `strategy.ExecuteAsync(...)` wrapped around
///         `BeginTransactionAsync` / two `SaveChangesAsync` / `CommitAsync`; and
///         `IsRowVersion()`, SQL Server's `rowversion` column, whose value the server
///         changes on every UPDATE.
/// Passes: offline - the model carries a rowversion concurrency token generated
///         OnAddOrUpdate, and the context's execution strategy retries on failure. At
///         L3 - a transfer moves money; a failure injected BETWEEN the two saves leaves
///         both balances exactly as they were, while a dirty read taken at that moment
///         proves the debit had really been written; and two interleaved updates make
///         the second saver throw DbUpdateConcurrencyException with no lost update.
/// Note:   Three traps, all measured.
///
///         (1) Once retries are enabled, `BeginTransactionAsync` on its own THROWS -
///         "the configured execution strategy 'SqlServerRetryingExecutionStrategy' does
///         not support user-initiated transactions". That is EF telling you a retry
///         would replay half a transaction. So "did the learner use the strategy" needs
///         no clever assertion: without it, the transfer cannot even start.
///
///         (2) `betweenSaves` and `afterLoad` are seams, and they exist because
///         concurrency tests that rely on wall-clock timing are flaky by construction.
///         There is no sleep and no second thread anywhere in this row: the test
///         supplies a callback, and the interleaving is therefore exactly as ordered as
///         a single-threaded program. Production callers pass null.
///
///         (3) A rowversion is generated by the SERVER, not by you - never assign it.
///         `[ConcurrencyCheck]` on Balance would also make two conflicting balance
///         updates collide, which is why the offline fact reads the column type rather
///         than merely asserting that something is a concurrency token.
/// </summary>
public static class Ex040_TransactionsAndConcurrency
{
    /// <summary>The RESOURCE name, hence the configuration key <c>ConnectionStrings:catalog</c>.</summary>
    public const string DatabaseResourceName = "catalog";

    public sealed class Account
    {
        public int Id { get; set; }
        public string Name { get; set; } = "";
        public decimal Balance { get; set; }

        /// <summary>
        /// The concurrency token. SQL Server assigns it on INSERT and reassigns it on
        /// every UPDATE; your code never writes it.
        /// </summary>
        public byte[] RowVersion { get; set; } = [];
    }

    public sealed class CatalogContext(DbContextOptions<CatalogContext> options) : DbContext(options)
    {
        public DbSet<Account> Accounts => Set<Account>();

        protected override void OnModelCreating(ModelBuilder modelBuilder)
            => ConfigureConcurrencyToken(modelBuilder);
    }

    /// <summary>
    /// Makes <see cref="Account.RowVersion"/> the entity's concurrency token, backed by
    /// SQL Server's <c>rowversion</c> type.
    /// </summary>
    private static void ConfigureConcurrencyToken(ModelBuilder modelBuilder)
    {
        // IsRowVersion() is three statements in one: the property becomes a concurrency
        // token, its store type becomes SQL Server's "rowversion", and its value is
        // generated OnAddOrUpdate - i.e. by the server, on every UPDATE. That last part
        // is what [ConcurrencyCheck] on Balance does not give you.
        modelBuilder.Entity<Account>()
                    .Property(account => account.RowVersion)
                    .IsRowVersion();
    }

    /// <summary>
    /// The options every operation in this row uses: SQL Server over
    /// <paramref name="connectionString"/>, with the retrying execution strategy on.
    /// </summary>
    public static DbContextOptions<CatalogContext> CreateOptions(string connectionString)
        => new DbContextOptionsBuilder<CatalogContext>()
            // Turning retries on is what makes the execution strategy a
            // SqlServerRetryingExecutionStrategy instead of the do-nothing default - and
            // what makes an un-wrapped BeginTransactionAsync throw rather than silently
            // work until the day a transient failure replays half of it.
            .UseSqlServer(connectionString, sqlServer => sqlServer.EnableRetryOnFailure())
            .Options;

    /// <summary>
    /// Moves <paramref name="amount"/> from one account to another as ONE unit: debit
    /// and credit are saved separately, inside a single explicit transaction, and the
    /// whole thing runs through the context's execution strategy so a transient failure
    /// replays all of it rather than half of it.
    /// </summary>
    /// <param name="betweenSaves">
    /// Test seam. Invoked after the debit has been saved and before the credit is - so
    /// throwing from it must leave the database exactly as it was found. Pass null in
    /// production code.
    /// </param>
    public static async Task TransferAsync(
        string connectionString,
        int fromAccountId,
        int toAccountId,
        decimal amount,
        Func<Task>? betweenSaves,
        CancellationToken cancellationToken)
    {
        await using var context = new CatalogContext(CreateOptions(connectionString));

        // The strategy owns the retry loop, so EVERYTHING that must replay together goes
        // inside its delegate - the transaction included. Calling BeginTransactionAsync
        // outside it throws: "The configured execution strategy
        // 'SqlServerRetryingExecutionStrategy' does not support user-initiated
        // transactions."
        var strategy = context.Database.CreateExecutionStrategy();

        await strategy.ExecuteAsync(async () =>
        {
            // A retry re-enters this delegate, so the entities are re-read here rather
            // than captured outside: replaying a transaction with stale, already-mutated
            // tracked entities would double the transfer.
            context.ChangeTracker.Clear();

            await using var transaction = await context.Database.BeginTransactionAsync(cancellationToken);

            var source = await context.Accounts.SingleAsync(a => a.Id == fromAccountId, cancellationToken);
            var destination = await context.Accounts.SingleAsync(a => a.Id == toAccountId, cancellationToken);

            source.Balance -= amount;
            await context.SaveChangesAsync(cancellationToken);

            if (betweenSaves is not null)
            {
                await betweenSaves();
            }

            destination.Balance += amount;
            await context.SaveChangesAsync(cancellationToken);

            // Two SaveChanges, one commit. Without the explicit transaction each save
            // would have committed on its own and the money would exist in neither
            // account - or in both.
            await transaction.CommitAsync(cancellationToken);
        });
    }

    /// <summary>
    /// Loads one account, adds <paramref name="delta"/> to its balance and saves.
    /// </summary>
    /// <param name="afterLoad">
    /// Test seam. Invoked while this context is holding a copy of the row and before it
    /// saves, so that another writer can get in first. Pass null in production code.
    /// </param>
    /// <returns>The row's new balance.</returns>
    /// <exception cref="DbUpdateConcurrencyException">
    /// Thrown when the row changed between the load and the save.
    /// </exception>
    public static async Task<decimal> AddToBalanceAsync(
        string connectionString,
        int accountId,
        decimal delta,
        Func<Task>? afterLoad,
        CancellationToken cancellationToken)
    {
        await using var context = new CatalogContext(CreateOptions(connectionString));

        var account = await context.Accounts.SingleAsync(a => a.Id == accountId, cancellationToken);

        // The window. Whatever runs here sees - and can change - the row this context is
        // now holding a stale copy of.
        if (afterLoad is not null)
        {
            await afterLoad();
        }

        account.Balance += delta;

        // EF adds "WHERE Id = @id AND RowVersion = @loadedRowVersion" and checks the
        // affected-row count. Zero rows means somebody else got there first, and EF says
        // so with DbUpdateConcurrencyException rather than by silently overwriting.
        await context.SaveChangesAsync(cancellationToken);
        return account.Balance;
    }

    public static void Configure(IDistributedApplicationBuilder builder)
    {
        builder.AddSqlServer("sqldata")
               .AddDatabase(DatabaseResourceName);
    }
}
